/**
 * Keeps a node mounted long enough for its exit transition to finish.
 *
 * # Why this exists rather than `AnimatePresence`
 *
 * This app animates exactly three things -- the log panel, the detail bar and
 * toasts -- and all of them animate opacity, size and transform, which the
 * browser does natively. Reaching for a library was costing **77KB of the
 * 499KB bundle (15.5%)**, measured by attributing generated bytes through the
 * sourcemap, and that is parsed on every boot by everyone, including the
 * majority of boots where nothing ever animates.
 *
 * Of everything the library did, only two parts are genuinely awkward, and both
 * come from the same fact: React removes a node the instant it stops rendering
 * it, so there is nothing left to animate on the way out.
 *
 *   1. The node has to stay mounted through the exit.
 *   2. The *data* it renders has to survive too. `logProject` is already null
 *      by the time the panel starts leaving, so something must hold the
 *      departing value or the exit renders an empty shell.
 *
 * That is this file. The animating itself is CSS, in `tokens.css`, using the
 * same duration and easing tokens as before -- so the timing is unchanged
 * rather than merely similar.
 *
 * # Why a timer and not `transitionend`
 *
 * `transitionend` fires once per animated property, so a panel animating
 * opacity and width fires twice and the handler has to know which is last. It
 * also does not fire at all when the property never actually changes -- an
 * element already at `opacity: 0`, or a transition interrupted by a re-render
 * -- and a missed event here means a node that is never unmounted. A timer of
 * the declared duration cannot get stuck. It reads the same token the CSS
 * does, so the two cannot drift apart without both being edited.
 *
 * # Reduced motion
 *
 * `prefers-reduced-motion` is read here as well as in CSS. The stylesheet
 * collapses the transition to ~0ms, so waiting the full duration before
 * unmounting would leave an invisible node in the tree -- still focusable,
 * still read by a screen reader -- for a fifth of a second after it visually
 * went away.
 */
import { useEffect, useRef, useState } from "react";

/** Mirrors `--duration-*` in `tokens.css`. Milliseconds, as the DOM takes them. */
export const DURATION = {
  instant: 80,
  fast: 140,
  base: 200,
  slow: 240,
} as const;

function exitDelay(ms: number): number {
  return window.matchMedia("(prefers-reduced-motion: reduce)").matches ? 0 : ms;
}

/**
 * A value that should animate in when it appears and out when it goes away.
 *
 * Returns the value to render -- which is the *departing* one during an exit --
 * and whether it should be in its open state. Apply `open` as the `is-open`
 * class alongside one of the `*-enter` classes in `tokens.css`.
 *
 * @param value   The live value, or null/undefined when nothing should show.
 * @param exitMs  Exit duration, from {@link DURATION}, matching the CSS.
 */
export function usePresentValue<T>(
  value: T | null | undefined,
  exitMs: number,
): { item: T | null; open: boolean } {
  const [item, setItem] = useState<T | null>(value ?? null);
  const timer = useRef<number | undefined>(undefined);

  useEffect(() => {
    window.clearTimeout(timer.current);
    if (value != null) {
      setItem(value);
      return;
    }
    timer.current = window.setTimeout(() => setItem(null), exitDelay(exitMs));
    return () => window.clearTimeout(timer.current);
  }, [value, exitMs]);

  // `open` follows the live value, not internal state, so reopening midway
  // through an exit reverses the transition from wherever it had got to --
  // handing the browser the new target class is exactly how it does that.
  // Waiting for an "exiting" state to finish first would make a fast toggle
  // feel stuck.
  return { item, open: value != null };
}

/**
 * The same idea for a keyed list: departed entries stay rendered, marked
 * closed, until their exit has run.
 *
 * @param items   The live list.
 * @param key     Stable identity for an entry.
 * @param exitMs  Exit duration, from {@link DURATION}, matching the CSS.
 */
export function usePresenceList<T>(
  items: readonly T[],
  key: (item: T) => string,
  exitMs: number,
): { item: T; open: boolean }[] {
  const [leaving, setLeaving] = useState<T[]>([]);
  const previous = useRef<readonly T[]>(items);
  const timers = useRef(new Map<string, number>());

  useEffect(() => {
    const live = new Set(items.map(key));
    const departed = previous.current.filter((item) => !live.has(key(item)));
    previous.current = items;

    // An entry that comes back before its exit finished should stop leaving,
    // otherwise it renders twice -- once live and once as a ghost.
    for (const item of items) {
      const k = key(item);
      const t = timers.current.get(k);
      if (t !== undefined) {
        window.clearTimeout(t);
        timers.current.delete(k);
        setLeaving((prev) => prev.filter((l) => key(l) !== k));
      }
    }

    if (departed.length === 0) return;
    setLeaving((prev) => [...prev, ...departed]);
    for (const item of departed) {
      const k = key(item);
      const t = window.setTimeout(() => {
        timers.current.delete(k);
        setLeaving((prev) => prev.filter((l) => key(l) !== k));
      }, exitDelay(exitMs));
      timers.current.set(k, t);
    }
  }, [items, key, exitMs]);

  useEffect(() => {
    const pending = timers.current;
    return () => {
      for (const t of pending.values()) window.clearTimeout(t);
      pending.clear();
    };
  }, []);

  // Leavers first: they were in the list before the survivors, and reordering
  // them to the end on their way out would make a dismissal look like the
  // stack shuffled.
  return [
    ...leaving.map((item) => ({ item, open: false })),
    ...items.map((item) => ({ item, open: true })),
  ];
}
